### ISSUE TITLE
Tag is misspelt

### ISSUE THREAD

**Issue by Sprinting** [Swap76/Learn-Deno#5]
Project tag "beginner-to-advance" is misspelt

**Comment by Swap76** [comment]
@Sprinting Thanks very much for the help I will update that :-)

**Comment by Swap76** [comment]
Have a look I have updated the tags

**Comment by Swap76** [comment]
@Sprinting Thanks for Contribution:-)

Looking forward to working with you

Star to the repo is highly appreciated.

**Comment by Sprinting** [comment]
Thank you, @Swap76. I came here from reddit. Unfortunately, I do not work with Javascript, so will not be able to contribute to this project.
